import {createHash} from "node:crypto";

import type {
    FoilCampaignConfig,
    FoilLabProjectConfig,
    FoilMachineConfig,
} from "./FoilLabTypes";
import {
    buildAnalysisTaskYaml,
    buildDescriptiveStatisticsRunner,
    buildResponseStatisticsRunner,
    isAnalysisEnabled,
} from "./analysisModules";
import {buildQueryArtifacts} from "./queryCatalog";

export interface FoilCompiledArtifact {
    relativePath: string;
    content: string;
}

export interface FoilCampaignCompilationPlan {
    campaignId: string;
    sourceHash: string;
    buildHash: string;
    resourceKey: string;
    artifacts: FoilCompiledArtifact[];
}

const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
const SAFE_SCHEMA = /^[A-Za-z_][A-Za-z0-9_]*$/;

function canonicalize(value: unknown): unknown {
    if (Array.isArray(value)) {
        return value.map(canonicalize);
    }
    if (value !== null && typeof value === "object") {
        return Object.fromEntries(
            Object.entries(value as Record<string, unknown>)
                .sort(([left], [right]) => left.localeCompare(right))
                .map(([key, child]) => [key, canonicalize(child)])
        );
    }
    return value;
}

function jsonString(value: unknown): string {
    const serialized = JSON.stringify(value);
    if (serialized === undefined) {
        throw new Error("FOIL Lab compiler could not serialize the campaign.");
    }
    return serialized;
}

function stableJson(value: unknown): string {
    return jsonString(canonicalize(value));
}

function prettyJson(value: unknown): string {
    return `${JSON.stringify(value, null, 4)}\n`;
}

function resourceKey(campaignId: string): string {
    return `foil_campaign_${campaignId.replace(/-/g, "_").toLowerCase()}`;
}

function yamlQuote(value: string): string {
    return jsonString(value);
}

function pythonLiteralJson(value: unknown): string {
    return jsonString(value).replace(/'''/g, "\\\\u0027\\\\u0027\\\\u0027");
}

function supportsSyntheticResponse(
    machine: FoilMachineConfig,
    campaign: FoilCampaignConfig
): boolean {
    return (
        machine.modelVersion === "wind_parametric_v1@0.1" &&
        campaign.technology === "EOLIEN" &&
        campaign.classification === "SYNTHETIC"
    );
}

function buildRunner(
    project: FoilLabProjectConfig,
    machine: FoilMachineConfig,
    campaign: FoilCampaignConfig,
    sourceHash: string
): string {
    return `"""Generated by FOIL Virtual Lab.

This runner always records the campaign contract and deterministic parameter design.
For the explicitly synthetic wind_parametric_v1@0.1 model it also evaluates a
bounded parametric response proxy. Those outputs are synthetic engineering proxies,
not Foil'O measurements or a validated commercial power curve.
"""

from __future__ import annotations

import hashlib
import itertools
import json
from datetime import datetime, timezone

from pyspark.sql import SparkSession

CAMPAIGN = json.loads(r'''${pythonLiteralJson(campaign)}''')
PROJECT = json.loads(r'''${pythonLiteralJson(project)}''')
MACHINE = json.loads(r'''${pythonLiteralJson(machine)}''')
SOURCE_HASH = "${sourceHash}"


def flatten_parameters(value, prefix=""):
    rows = []
    if isinstance(value, dict):
        for key in sorted(value):
            path = f"{prefix}.{key}" if prefix else key
            rows.extend(flatten_parameters(value[key], path))
        return rows
    if isinstance(value, list):
        for index, item in enumerate(value):
            rows.append((prefix, index, item))
        return rows
    rows.append((prefix, 0, value))
    return rows


def scenario_dimensions(value, prefix=""):
    dimensions = []
    if isinstance(value, dict):
        for key in sorted(value):
            path = f"{prefix}.{key}" if prefix else key
            dimensions.extend(scenario_dimensions(value[key], path))
        return dimensions
    values = value if isinstance(value, list) else [value]
    dimensions.append((prefix, values))
    return dimensions


def build_scenarios(test):
    dimensions = scenario_dimensions(test)
    if any(len(values) == 0 for _, values in dimensions):
        return []

    paths = [path for path, _ in dimensions]
    choices = [values for _, values in dimensions]
    combinations = itertools.product(*choices) if choices else [()]
    scenarios = []
    for scenario_index, combination in enumerate(combinations):
        parameters = dict(zip(paths, combination))
        canonical = json.dumps(
            parameters,
            sort_keys=True,
            separators=(",", ":"),
        )
        scenario_id = hashlib.sha256(
            f"{SOURCE_HASH}:{canonical}".encode("utf8")
        ).hexdigest()[:20]
        scenarios.append((scenario_index, scenario_id, parameters, canonical))
    return scenarios


def require_numeric(parameters, path):
    value = parameters.get(path)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"Expected numeric campaign parameter: {path}")
    return float(value)


def synthetic_wind_response(parameters):
    if (
        MACHINE.get("modelVersion") != "wind_parametric_v1@0.1"
        or CAMPAIGN.get("classification") != "SYNTHETIC"
    ):
        return None

    wind_speed = require_numeric(parameters, "environment.windSpeedMs")
    air_density = require_numeric(parameters, "environment.airDensityKgM3")
    effective_area = require_numeric(parameters, "machine.effectiveAreaM2")
    pitch_deg = require_numeric(parameters, "control.pitchDeg")
    frequency_hz = require_numeric(parameters, "control.frequencyHz")
    phase_deg_value = parameters.get("control.phaseDeg")
    phase_deg = None
    if phase_deg_value is not None:
        if isinstance(phase_deg_value, bool) or not isinstance(
            phase_deg_value, (int, float)
        ):
            raise ValueError("Expected numeric campaign parameter: control.phaseDeg")
        phase_deg = float(phase_deg_value)
    conversion_efficiency = require_numeric(
        parameters, "conversion.efficiencyProxy"
    )
    duration_h = require_numeric(parameters, "experiment.durationH")

    cp_reference = 0.40
    cp_cap = 0.44
    pitch_optimum_deg = 15.0
    pitch_width_deg = 20.0
    frequency_optimum_hz = 0.8
    frequency_width_hz = 0.6

    pitch_factor = max(
        0.0,
        1.0 - ((pitch_deg - pitch_optimum_deg) / pitch_width_deg) ** 2,
    )
    frequency_factor = max(
        0.0,
        1.0 - ((frequency_hz - frequency_optimum_hz) / frequency_width_hz) ** 2,
    )

    available_fluid_power_kw = (
        0.5 * air_density * effective_area * abs(wind_speed) ** 3 / 1000.0
    )
    capture_proxy = min(
        cp_cap,
        cp_reference * pitch_factor * frequency_factor,
    )
    mechanical_power_proxy_kw = available_fluid_power_kw * capture_proxy
    electrical_power_proxy_kw = (
        mechanical_power_proxy_kw * conversion_efficiency
    )
    efficiency_proxy = capture_proxy * conversion_efficiency
    energy_proxy_kwh = electrical_power_proxy_kw * duration_h
    load_proxy_n = 0.5 * air_density * effective_area * wind_speed ** 2

    assumptions = {
        "cp_reference": cp_reference,
        "cp_cap": cp_cap,
        "cp_reference_source": "SRC-WIND-TECH-20260714",
        "cp_reference_scope": "EXTERNAL_LITERATURE_ANCHOR",
        "pitch_optimum_deg": pitch_optimum_deg,
        "pitch_width_deg": pitch_width_deg,
        "frequency_optimum_hz": frequency_optimum_hz,
        "frequency_width_hz": frequency_width_hz,
        "turbulence_mean_effect_encoded": False,
        "phase_deg": phase_deg,
        "phase_source": (
            "WIND-014_SOURCE_BACKED_BASELINE"
            if phase_deg == 90.0
            else (
                "SYNTHETIC_SENSITIVITY_OR_OTHER"
                if phase_deg is not None
                else "NOT_PROVIDED"
            )
        ),
        "phase_response_effect_encoded": False,
        "yaw_architecture_effect_encoded": False,
        "measured_power_curve": False,
        "validated_foil_o_cp": False,
    }

    return {
        "available_fluid_power_kw": available_fluid_power_kw,
        "capture_proxy": capture_proxy,
        "mechanical_power_proxy_kw": mechanical_power_proxy_kw,
        "electrical_power_proxy_kw": electrical_power_proxy_kw,
        "efficiency_proxy": efficiency_proxy,
        "energy_proxy_kwh": energy_proxy_kwh,
        "load_proxy_n": load_proxy_n,
        "assumptions_json": json.dumps(assumptions, sort_keys=True),
    }


def main():
    spark = SparkSession.builder.getOrCreate()
    gold_schema = PROJECT["databricks"]["goldSchema"]
    catalog = PROJECT["databricks"].get("catalog")
    campaign_id = CAMPAIGN["campaignId"]
    compiled_at = datetime.now(timezone.utc).isoformat()

    if catalog:
        spark.sql(f"USE CATALOG \`{catalog}\`")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS \`{gold_schema}\`")
    spark.sql(
        f"""
        CREATE TABLE IF NOT EXISTS \`{gold_schema}\`.campaign_registry (
            campaign_id STRING,
            source_hash STRING,
            technology STRING,
            machine_id STRING,
            machine_model_version STRING,
            machine_json STRING,
            classification STRING,
            objective STRING,
            analysis_modules_json STRING,
            compiled_at_utc STRING
        ) USING DELTA
        """
    )
    spark.sql(
        f"""
        CREATE TABLE IF NOT EXISTS \`{gold_schema}\`.campaign_parameters (
            campaign_id STRING,
            source_hash STRING,
            parameter_path STRING,
            value_index INT,
            parameter_value_json STRING,
            parameter_value_numeric DOUBLE
        ) USING DELTA
        """
    )

    synthetic_response_enabled = (
        MACHINE.get("modelVersion") == "wind_parametric_v1@0.1"
        and CAMPAIGN.get("classification") == "SYNTHETIC"
    )
    if synthetic_response_enabled:
        spark.sql(
            f"""
            CREATE TABLE IF NOT EXISTS \`{gold_schema}\`.scenario_response_results (
                campaign_id STRING,
                source_hash STRING,
                scenario_id STRING,
                model_version STRING,
                result_classification STRING,
                available_fluid_power_kw DOUBLE,
                capture_proxy DOUBLE,
                mechanical_power_proxy_kw DOUBLE,
                electrical_power_proxy_kw DOUBLE,
                efficiency_proxy DOUBLE,
                energy_proxy_kwh DOUBLE,
                load_proxy_n DOUBLE,
                assumptions_json STRING
            ) USING DELTA
            """
        )

    registry_rows = [
        (
            campaign_id,
            SOURCE_HASH,
            CAMPAIGN["technology"],
            CAMPAIGN["machineId"],
            MACHINE["modelVersion"],
            json.dumps(MACHINE, sort_keys=True),
            CAMPAIGN["classification"],
            CAMPAIGN["objective"],
            json.dumps(CAMPAIGN.get("analyses", []), sort_keys=True),
            compiled_at,
        )
    ]
    registry = spark.createDataFrame(
        registry_rows,
        schema=(
            "campaign_id string, source_hash string, technology string, "
            "machine_id string, machine_model_version string, machine_json string, "
            "classification string, objective string, "
            "analysis_modules_json string, compiled_at_utc string"
        ),
    )
    registry.createOrReplaceTempView("foil_compiled_campaign_registry")
    spark.sql(
        f"""
        MERGE INTO \`{gold_schema}\`.campaign_registry target
        USING foil_compiled_campaign_registry source
        ON target.campaign_id = source.campaign_id
           AND target.source_hash = source.source_hash
        WHEN MATCHED THEN UPDATE SET *
        WHEN NOT MATCHED THEN INSERT *
        """
    )

    parameter_rows = []
    for parameter_path, value_index, value in flatten_parameters(
        CAMPAIGN.get("test", {})
    ):
        numeric = (
            float(value)
            if isinstance(value, (int, float)) and not isinstance(value, bool)
            else None
        )
        parameter_rows.append(
            (
                campaign_id,
                SOURCE_HASH,
                parameter_path,
                value_index,
                json.dumps(value, sort_keys=True),
                numeric,
            )
        )

    if parameter_rows:
        parameters = spark.createDataFrame(
            parameter_rows,
            schema=(
                "campaign_id string, source_hash string, parameter_path string, "
                "value_index int, parameter_value_json string, "
                "parameter_value_numeric double"
            ),
        )
        parameters.createOrReplaceTempView("foil_compiled_campaign_parameters")
        spark.sql(
            f"""
            MERGE INTO \`{gold_schema}\`.campaign_parameters target
            USING foil_compiled_campaign_parameters source
            ON target.campaign_id = source.campaign_id
               AND target.source_hash = source.source_hash
               AND target.parameter_path = source.parameter_path
               AND target.value_index = source.value_index
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """
        )

    scenarios = build_scenarios(CAMPAIGN.get("test", {}))
    response_rows = []
    scenario_rows = [
        (campaign_id, SOURCE_HASH, index, scenario_id, canonical)
        for index, scenario_id, _, canonical in scenarios
    ]
    if scenario_rows:
        scenario_frame = spark.createDataFrame(
            scenario_rows,
            schema=(
                "campaign_id string, source_hash string, scenario_index int, "
                "scenario_id string, parameters_json string"
            ),
        )
        scenario_frame.createOrReplaceTempView("foil_campaign_scenarios")
        spark.sql(
            f"""
            MERGE INTO \`{gold_schema}\`.campaign_scenarios target
            USING foil_campaign_scenarios source
            ON target.campaign_id = source.campaign_id
               AND target.source_hash = source.source_hash
               AND target.scenario_id = source.scenario_id
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """
        )

        scenario_parameter_rows = []
        for _, scenario_id, parameters, _ in scenarios:
            for parameter_path, value in sorted(parameters.items()):
                numeric = (
                    float(value)
                    if isinstance(value, (int, float)) and not isinstance(value, bool)
                    else None
                )
                scenario_parameter_rows.append(
                    (
                        campaign_id,
                        SOURCE_HASH,
                        scenario_id,
                        parameter_path,
                        json.dumps(value, sort_keys=True),
                        numeric,
                    )
                )
        scenario_parameters = spark.createDataFrame(
            scenario_parameter_rows,
            schema=(
                "campaign_id string, source_hash string, scenario_id string, "
                "parameter_path string, parameter_value_json string, "
                "parameter_value_numeric double"
            ),
        )
        scenario_parameters.createOrReplaceTempView("foil_scenario_parameters")
        spark.sql(
            f"""
            MERGE INTO \`{gold_schema}\`.scenario_parameters target
            USING foil_scenario_parameters source
            ON target.campaign_id = source.campaign_id
               AND target.source_hash = source.source_hash
               AND target.scenario_id = source.scenario_id
               AND target.parameter_path = source.parameter_path
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """
        )

    if scenario_rows and synthetic_response_enabled:
        for _, scenario_id, parameters, _ in scenarios:
            result = synthetic_wind_response(parameters)
            if result is None:
                continue
            response_rows.append(
                (
                    campaign_id,
                    SOURCE_HASH,
                    scenario_id,
                    MACHINE["modelVersion"],
                    "SYNTHETIC_MODEL_OUTPUT",
                    result["available_fluid_power_kw"],
                    result["capture_proxy"],
                    result["mechanical_power_proxy_kw"],
                    result["electrical_power_proxy_kw"],
                    result["efficiency_proxy"],
                    result["energy_proxy_kwh"],
                    result["load_proxy_n"],
                    result["assumptions_json"],
                )
            )

        responses = spark.createDataFrame(
            response_rows,
            schema=(
                "campaign_id string, source_hash string, scenario_id string, "
                "model_version string, result_classification string, "
                "available_fluid_power_kw double, capture_proxy double, "
                "mechanical_power_proxy_kw double, electrical_power_proxy_kw double, "
                "efficiency_proxy double, energy_proxy_kwh double, load_proxy_n double, "
                "assumptions_json string"
            ),
        )
        responses.createOrReplaceTempView("foil_scenario_response_results")
        spark.sql(
            f"""
            MERGE INTO \`{gold_schema}\`.scenario_response_results target
            USING foil_scenario_response_results source
            ON target.campaign_id = source.campaign_id
               AND target.source_hash = source.source_hash
               AND target.scenario_id = source.scenario_id
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """
        )

    print(
        json.dumps(
            {
                "campaign_id": campaign_id,
                "source_hash": SOURCE_HASH,
                "gold_schema": gold_schema,
                "parameter_rows": len(parameter_rows),
                "scenario_count": len(scenarios),
                "response_rows": len(response_rows),
                "status": (
                    "SYNTHETIC_RESPONSE_PUBLISHED"
                    if response_rows
                    else "CAMPAIGN_CONTRACT_REGISTERED"
                ),
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
`;
}

function buildJobYaml(
    campaign: FoilCampaignConfig,
    resource: string,
    includeResponseStatistics: boolean
): string {
    return `resources:
  jobs:
    ${resource}:
      name: ${yamlQuote(`FOIL Campaign - ${campaign.campaignId}`)}
      description: ${yamlQuote("Generated FOIL campaign job")}
      tasks:
        - task_key: register_campaign_contract
          spark_python_task:
            python_file: ../src/run_campaign.py
          environment_key: default${buildAnalysisTaskYaml(
              campaign,
              includeResponseStatistics
          )}
      environments:
        - environment_key: default
          spec:
            environment_version: "2"
`;
}

function buildDashboardIntent(
    project: FoilLabProjectConfig,
    machine: FoilMachineConfig,
    campaign: FoilCampaignConfig
): unknown {
    const datasets: Array<Record<string, unknown>> = [
        {
            id: "campaign_registry",
            table: `${project.databricks.goldSchema}.campaign_registry`,
        },
        {
            id: "campaign_parameters",
            table: `${project.databricks.goldSchema}.campaign_parameters`,
        },
        {
            id: "campaign_scenarios",
            table: `${project.databricks.goldSchema}.campaign_scenarios`,
            scope: "EXPERIMENT_DESIGN_MATRIX",
        },
        {
            id: "scenario_parameters",
            table: `${project.databricks.goldSchema}.scenario_parameters`,
            scope: "EXPERIMENT_DESIGN_MATRIX",
        },
    ];
    if (supportsSyntheticResponse(machine, campaign)) {
        datasets.push({
            id: "scenario_response_results",
            table: `${project.databricks.goldSchema}.scenario_response_results`,
            scope: "SYNTHETIC_PARAMETRIC_RESPONSE",
        });
    }
    if (
        supportsSyntheticResponse(machine, campaign) &&
        isAnalysisEnabled(campaign, "response_statistics")
    ) {
        datasets.push({
            id: "campaign_response_statistics",
            table: `${project.databricks.goldSchema}.campaign_response_statistics`,
            scope: "SYNTHETIC_MODEL_OUTPUT",
        });
    }
    if (isAnalysisEnabled(campaign, "descriptive_statistics")) {
        datasets.push({
            id: "campaign_design_statistics",
            table: `${project.databricks.goldSchema}.campaign_design_statistics`,
            scope: "EXPERIMENT_DESIGN_PARAMETERS",
        });
    }

    return {
        version: "0.1",
        campaignId: campaign.campaignId,
        enabled: campaign.outputs?.aiBiDashboard === true,
        goldSchema: project.databricks.goldSchema,
        datasets,
        note: "Intent only. A later compiler stage emits the .lvdash.json asset.",
    };
}

function buildAppPageIntent(
    project: FoilLabProjectConfig,
    machine: FoilMachineConfig,
    campaign: FoilCampaignConfig
): unknown {
    const sections = [
        "campaign_contract",
        "parameters",
        "scenario_matrix",
        "analysis_plan",
    ];
    if (supportsSyntheticResponse(machine, campaign)) {
        sections.push("synthetic_response");
    }
    if (
        supportsSyntheticResponse(machine, campaign) &&
        isAnalysisEnabled(campaign, "response_statistics")
    ) {
        sections.push("response_statistics");
    }
    if (isAnalysisEnabled(campaign, "descriptive_statistics")) {
        sections.push("design_statistics");
    }

    return {
        version: "0.1",
        campaignId: campaign.campaignId,
        enabled: campaign.outputs?.streamlitApp === true,
        appResource: project.databricks.appResource,
        goldSchema: project.databricks.goldSchema,
        sections,
        note: "Consumed by the persistent FOIL Streamlit app; not a standalone app.",
    };
}

export function compileCampaign(
    project: FoilLabProjectConfig,
    machine: FoilMachineConfig,
    campaign: FoilCampaignConfig
): FoilCampaignCompilationPlan {
    if (!SAFE_ID.test(campaign.campaignId)) {
        throw new Error(
            "Campaign id is not safe for generated Databricks resources."
        );
    }
    if (!SAFE_SCHEMA.test(project.databricks.goldSchema)) {
        throw new Error("Gold schema is not a safe Unity Catalog identifier.");
    }
    if (
        project.databricks.catalog !== undefined &&
        project.databricks.catalog.length > 0 &&
        !SAFE_SCHEMA.test(project.databricks.catalog)
    ) {
        throw new Error("Catalog is not a safe Unity Catalog identifier.");
    }

    if (machine.machineId !== campaign.machineId) {
        throw new Error(
            "Campaign machineId does not match the supplied machine profile."
        );
    }

    const sourceHash = createHash("sha256")
        .update(stableJson({machine, campaign}), "utf8")
        .digest("hex");
    const buildHash = createHash("sha256")
        .update(stableJson({project, machine, campaign}), "utf8")
        .digest("hex");
    const resource = resourceKey(campaign.campaignId);
    const descriptiveStatistics = buildDescriptiveStatisticsRunner(
        project,
        campaign,
        sourceHash
    );
    const syntheticResponseEnabled = supportsSyntheticResponse(
        machine,
        campaign
    );
    const responseStatistics = syntheticResponseEnabled
        ? buildResponseStatisticsRunner(project, campaign, sourceHash)
        : undefined;
    const manifest = {
        compilerVersion: "0.4",
        campaignId: campaign.campaignId,
        technology: campaign.technology,
        machineId: campaign.machineId,
        machineModelVersion: machine.modelVersion,
        controlProvenance: machine.control ?? null,
        classification: campaign.classification,
        sourceHash,
        buildHash,
        resourceKey: resource,
        catalog: project.databricks.catalog ?? null,
        outputContract: {
            campaignRegistry: `${project.databricks.goldSchema}.campaign_registry`,
            campaignParameters: `${project.databricks.goldSchema}.campaign_parameters`,
            campaignScenarios: `${project.databricks.goldSchema}.campaign_scenarios`,
            scenarioParameters: `${project.databricks.goldSchema}.scenario_parameters`,
            scenarioResponse: syntheticResponseEnabled
                ? `${project.databricks.goldSchema}.scenario_response_results`
                : undefined,
            responseStatistics:
                responseStatistics === undefined
                    ? undefined
                    : `${project.databricks.goldSchema}.campaign_response_statistics`,
            designStatistics:
                descriptiveStatistics === undefined
                    ? undefined
                    : `${project.databricks.goldSchema}.campaign_design_statistics`,
        },
        analysisModules: campaign.analyses.map((analysis) => ({
            id: analysis.module,
            enabled: analysis.enabled !== false,
            compiled:
                analysis.module === "descriptive_statistics"
                    ? descriptiveStatistics !== undefined
                    : analysis.module === "response_statistics"
                      ? responseStatistics !== undefined
                      : false,
        })),
        safety: {
            executesArbitraryImportedScripts: false,
            engineeringResultsGeneratedByThisStage: syntheticResponseEnabled,
            engineeringResultClassification: syntheticResponseEnabled
                ? "SYNTHETIC_MODEL_OUTPUT"
                : undefined,
            analysisScope: syntheticResponseEnabled
                ? "SYNTHETIC_PARAMETRIC_RESPONSE"
                : descriptiveStatistics === undefined
                  ? "CAMPAIGN_CONTRACT_ONLY"
                  : "EXPERIMENT_DESIGN_PARAMETERS",
        },
    };

    const queryArtifacts = buildQueryArtifacts(project, campaign, {
        includeSyntheticResponse: syntheticResponseEnabled,
        includeResponseStatistics: responseStatistics !== undefined,
    });
    const artifacts: FoilCompiledArtifact[] = [
        {
            relativePath: "manifest.json",
            content: prettyJson(manifest),
        },
        {
            relativePath: "campaign.json",
            content: prettyJson(campaign),
        },
        {
            relativePath: "src/run_campaign.py",
            content: buildRunner(project, machine, campaign, sourceHash),
        },
        {
            relativePath: "resources/campaign.job.yml",
            content: buildJobYaml(
                campaign,
                resource,
                responseStatistics !== undefined
            ),
        },
        {
            relativePath: "dashboard/dashboard-intent.json",
            content: prettyJson(
                buildDashboardIntent(project, machine, campaign)
            ),
        },
        {
            relativePath: "ui/campaign-page.json",
            content: prettyJson(buildAppPageIntent(project, machine, campaign)),
        },
        {
            relativePath: "bundle-include.txt",
            content: `include:\n  - .foil-lab/build/${campaign.campaignId}/resources/campaign.job.yml\n`,
        },
    ];

    artifacts.push(...queryArtifacts);

    if (descriptiveStatistics !== undefined) {
        artifacts.push({
            relativePath: "src/analyses/descriptive_statistics.py",
            content: descriptiveStatistics,
        });
    }

    if (responseStatistics !== undefined) {
        artifacts.push({
            relativePath: "src/analyses/response_statistics.py",
            content: responseStatistics,
        });
    }

    return {
        campaignId: campaign.campaignId,
        sourceHash,
        buildHash,
        resourceKey: resource,
        artifacts,
    };
}
