import {createHash} from "node:crypto";

import type {
    FoilCampaignConfig,
    FoilLabProjectConfig,
} from "./FoilLabTypes";

export interface FoilCompiledArtifact {
    relativePath: string;
    content: string;
}

export interface FoilCampaignCompilationPlan {
    campaignId: string;
    sourceHash: string;
    resourceKey: string;
    artifacts: FoilCompiledArtifact[];
}

const SAFE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
const SAFE_SCHEMA = /^[A-Za-z_][A-Za-z0-9_]*$/;

function canonicalize(value: unknown): unknown {
    if (Array.isArray(value)) {
        return value.map(canonicalize);
    }
    if (value !== null && typeof value === "object") {
        return Object.fromEntries(
            Object.entries(value as Record<string, unknown>)
                .sort(([left], [right]) => left.localeCompare(right))
                .map(([key, child]) => [key, canonicalize(child)])
        );
    }
    return value;
}

function jsonString(value: unknown): string {
    const serialized = JSON.stringify(value);
    if (serialized === undefined) {
        throw new Error("FOIL Lab compiler could not serialize the campaign.");
    }
    return serialized;
}

function stableJson(value: unknown): string {
    return jsonString(canonicalize(value));
}

function prettyJson(value: unknown): string {
    return \`\${JSON.stringify(value, null, 4)}\\n\`;
}

function resourceKey(campaignId: string): string {
    return \`foil_campaign_\${campaignId.replace(/-/g, "_").toLowerCase()}\`;
}

function yamlQuote(value: string): string {
    return jsonString(value);
}

function pythonLiteralJson(value: unknown): string {
    return jsonString(value).replace(/'''/g, "\\\\u0027\\\\u0027\\\\u0027");
}

function buildRunner(
    project: FoilLabProjectConfig,
    campaign: FoilCampaignConfig,
    sourceHash: string
): string {
    return \`"""Generated by FOIL Virtual Lab.

This runner records the campaign contract and parameter design only. It does not
claim physical, statistical, or ML results. Analysis modules publish those outputs
separately after validation.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone

from pyspark.sql import SparkSession

CAMPAIGN = json.loads(r'''\${pythonLiteralJson(campaign)}''')
PROJECT = json.loads(r'''\${pythonLiteralJson(project)}''')
SOURCE_HASH = "\${sourceHash}"


def flatten_parameters(value, prefix=""):
    rows = []
    if isinstance(value, dict):
        for key in sorted(value):
            path = f"{prefix}.{key}" if prefix else key
            rows.extend(flatten_parameters(value[key], path))
        return rows
    if isinstance(value, list):
        for index, item in enumerate(value):
            rows.append((prefix, index, item))
        return rows
    rows.append((prefix, 0, value))
    return rows


def main():
    spark = SparkSession.builder.getOrCreate()
    gold_schema = PROJECT["databricks"]["goldSchema"]
    campaign_id = CAMPAIGN["campaignId"]
    compiled_at = datetime.now(timezone.utc).isoformat()

    spark.sql(f"CREATE SCHEMA IF NOT EXISTS \`{gold_schema}\`")
    spark.sql(
        f"""
        CREATE TABLE IF NOT EXISTS \`{gold_schema}\`.campaign_registry (
            campaign_id STRING,
            source_hash STRING,
            technology STRING,
            machine_id STRING,
            classification STRING,
            objective STRING,
            analysis_modules_json STRING,
            compiled_at_utc STRING
        ) USING DELTA
        """
    )
    spark.sql(
        f"""
        CREATE TABLE IF NOT EXISTS \`{gold_schema}\`.campaign_parameters (
            campaign_id STRING,
            source_hash STRING,
            parameter_path STRING,
            value_index INT,
            parameter_value_json STRING,
            parameter_value_numeric DOUBLE
        ) USING DELTA
        """
    )

    registry_rows = [
        (
            campaign_id,
            SOURCE_HASH,
            CAMPAIGN["technology"],
            CAMPAIGN["machineId"],
            CAMPAIGN["classification"],
            CAMPAIGN["objective"],
            json.dumps(CAMPAIGN.get("analyses", []), sort_keys=True),
            compiled_at,
        )
    ]
    registry = spark.createDataFrame(
        registry_rows,
        schema=(
            "campaign_id string, source_hash string, technology string, "
            "machine_id string, classification string, objective string, "
            "analysis_modules_json string, compiled_at_utc string"
        ),
    )
    registry.createOrReplaceTempView("foil_compiled_campaign_registry")
    spark.sql(
        f"""
        MERGE INTO \`{gold_schema}\`.campaign_registry target
        USING foil_compiled_campaign_registry source
        ON target.campaign_id = source.campaign_id
           AND target.source_hash = source.source_hash
        WHEN MATCHED THEN UPDATE SET *
        WHEN NOT MATCHED THEN INSERT *
        """
    )

    parameter_rows = []
    for parameter_path, value_index, value in flatten_parameters(
        CAMPAIGN.get("test", {})
    ):
        numeric = (
            float(value)
            if isinstance(value, (int, float)) and not isinstance(value, bool)
            else None
        )
        parameter_rows.append(
            (
                campaign_id,
                SOURCE_HASH,
                parameter_path,
                value_index,
                json.dumps(value, sort_keys=True),
                numeric,
            )
        )

    if parameter_rows:
        parameters = spark.createDataFrame(
            parameter_rows,
            schema=(
                "campaign_id string, source_hash string, parameter_path string, "
                "value_index int, parameter_value_json string, "
                "parameter_value_numeric double"
            ),
        )
        parameters.createOrReplaceTempView("foil_compiled_campaign_parameters")
        spark.sql(
            f"""
            MERGE INTO \`{gold_schema}\`.campaign_parameters target
            USING foil_compiled_campaign_parameters source
            ON target.campaign_id = source.campaign_id
               AND target.source_hash = source.source_hash
               AND target.parameter_path = source.parameter_path
               AND target.value_index = source.value_index
            WHEN MATCHED THEN UPDATE SET *
            WHEN NOT MATCHED THEN INSERT *
            """
        )

    print(
        json.dumps(
            {
                "campaign_id": campaign_id,
                "source_hash": SOURCE_HASH,
                "gold_schema": gold_schema,
                "parameter_rows": len(parameter_rows),
                "status": "CAMPAIGN_CONTRACT_REGISTERED",
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
\`;
}

function buildJobYaml(
    campaign: FoilCampaignConfig,
    resource: string
): string {
    return \`resources:
  jobs:
    \${resource}:
      name: \${yamlQuote(\`FOIL Campaign - \${campaign.campaignId}\`)}
      description: \${yamlQuote("Generated FOIL campaign contract registration job")}
      tasks:
        - task_key: register_campaign_contract
          spark_python_task:
            python_file: ../src/run_campaign.py
          environment_key: default
      environments:
        - environment_key: default
          spec:
            environment_version: "2"
\`;
}

function buildDashboardIntent(
    project: FoilLabProjectConfig,
    campaign: FoilCampaignConfig
): unknown {
    return {
        version: "0.1",
        campaignId: campaign.campaignId,
        enabled: campaign.outputs?.aiBiDashboard === true,
        goldSchema: project.databricks.goldSchema,
        datasets: [
            {
                id: "campaign_registry",
                table: \`\${project.databricks.goldSchema}.campaign_registry\`,
            },
            {
                id: "campaign_parameters",
                table: \`\${project.databricks.goldSchema}.campaign_parameters\`,
            },
        ],
        note: "Intent only. A later compiler stage emits the .lvdash.json asset.",
    };
}

function buildAppPageIntent(
    project: FoilLabProjectConfig,
    campaign: FoilCampaignConfig
): unknown {
    return {
        version: "0.1",
        campaignId: campaign.campaignId,
        enabled: campaign.outputs?.streamlitApp === true,
        appResource: project.databricks.appResource,
        goldSchema: project.databricks.goldSchema,
        sections: ["campaign_contract", "parameters", "analysis_plan"],
        note: "Consumed by the persistent FOIL Streamlit app; not a standalone app.",
    };
}

export function compileCampaign(
    project: FoilLabProjectConfig,
    campaign: FoilCampaignConfig
): FoilCampaignCompilationPlan {
    if (!SAFE_ID.test(campaign.campaignId)) {
        throw new Error("Campaign id is not safe for generated Databricks resources.");
    }
    if (!SAFE_SCHEMA.test(project.databricks.goldSchema)) {
        throw new Error("Gold schema is not a safe Unity Catalog identifier.");
    }

    const sourceHash = createHash("sha256")
        .update(stableJson({project, campaign}), "utf8")
        .digest("hex");
    const resource = resourceKey(campaign.campaignId);
    const manifest = {
        compilerVersion: "0.1",
        campaignId: campaign.campaignId,
        technology: campaign.technology,
        machineId: campaign.machineId,
        classification: campaign.classification,
        sourceHash,
        resourceKey: resource,
        outputContract: {
            campaignRegistry: \`\${project.databricks.goldSchema}.campaign_registry\`,
            campaignParameters: \`\${project.databricks.goldSchema}.campaign_parameters\`,
        },
        safety: {
            executesArbitraryImportedScripts: false,
            scientificResultsGeneratedByThisStage: false,
        },
    };

    return {
        campaignId: campaign.campaignId,
        sourceHash,
        resourceKey: resource,
        artifacts: [
            {
                relativePath: "manifest.json",
                content: prettyJson(manifest),
            },
            {
                relativePath: "campaign.json",
                content: prettyJson(campaign),
            },
            {
                relativePath: "src/run_campaign.py",
                content: buildRunner(project, campaign, sourceHash),
            },
            {
                relativePath: "resources/campaign.job.yml",
                content: buildJobYaml(campaign, resource),
            },
            {
                relativePath: "dashboard/dashboard-intent.json",
                content: prettyJson(buildDashboardIntent(project, campaign)),
            },
            {
                relativePath: "ui/campaign-page.json",
                content: prettyJson(buildAppPageIntent(project, campaign)),
            },
            {
                relativePath: "bundle-include.txt",
                content: \`include:\\n  - ./.foil-lab/build/\${campaign.campaignId}/resources/campaign.job.yml\\n\`,
            },
        ],
    };
}
