import type {FoilCampaignConfig, FoilLabProjectConfig} from "./FoilLabTypes";

export interface FoilQueryArtifact {
    relativePath: string;
    content: string;
}

export interface FoilQueryOptions {
    includeSyntheticResponse?: boolean;
    includeResponseStatistics?: boolean;
}

function quoteIdentifier(value: string): string {
    return "`" + value.replace(/`/g, "``") + "`";
}

function fullTable(project: FoilLabProjectConfig, table: string): string {
    const schemaAndTable = `${quoteIdentifier(
        project.databricks.goldSchema
    )}.${quoteIdentifier(table)}`;
    return project.databricks.catalog
        ? `${quoteIdentifier(project.databricks.catalog)}.${schemaAndTable}`
        : schemaAndTable;
}

function sqlHeader(campaign: FoilCampaignConfig): string {
    return `-- Generated by FOIL Virtual Lab
-- campaign_id: ${campaign.campaignId}
-- Read-only query contract. Engineering calculations belong in governed Gold logic.

`;
}

export function buildQueryArtifacts(
    project: FoilLabProjectConfig,
    campaign: FoilCampaignConfig,
    options: FoilQueryOptions = {}
): FoilQueryArtifact[] {
    const registry = fullTable(project, "campaign_registry");
    const parameters = fullTable(project, "campaign_parameters");
    const scenarios = fullTable(project, "campaign_scenarios");
    const scenarioParameters = fullTable(project, "scenario_parameters");
    const statistics = fullTable(project, "campaign_design_statistics");
    const responses = fullTable(project, "scenario_response_results");
    const responseStatistics = fullTable(
        project,
        "campaign_response_statistics"
    );

    const catalog = {
        version: "0.1",
        campaignId: campaign.campaignId,
        parameterStyle: "named",
        parameters: {
            campaign_id: {
                type: "STRING",
                default: campaign.campaignId,
            },
        },
        queries: [
            {
                id: "campaign_summary",
                file: "campaign_summary.sql",
                grain: "one row per campaign contract version",
                datasets: ["campaign_registry"],
            },
            {
                id: "scenario_matrix",
                file: "scenario_matrix.sql",
                grain: "one row per deterministic scenario",
                datasets: ["campaign_scenarios"],
            },
            {
                id: "scenario_parameters",
                file: "scenario_parameters.sql",
                grain: "one row per scenario and parameter",
                datasets: ["scenario_parameters"],
            },
            {
                id: "design_statistics",
                file: "design_statistics.sql",
                grain: "one row per numeric experiment-design parameter",
                datasets: ["campaign_design_statistics"],
                optional: true,
            },
        ],
        relationships: [
            {
                left: "campaign_registry.campaign_id",
                right: "campaign_scenarios.campaign_id",
                cardinality: "one_to_many",
            },
            {
                left: "campaign_scenarios.scenario_id",
                right: "scenario_parameters.scenario_id",
                cardinality: "one_to_many",
            },
        ],
        safety: {
            readOnly: true,
            sourceLayer: "GOLD",
            measuredEvidenceImplied: false,
        },
    };

    if (options.includeSyntheticResponse === true) {
        catalog.queries.push({
            id: "scenario_response",
            file: "scenario_response.sql",
            grain: "one row per synthetic scenario response",
            datasets: ["scenario_response_results"],
        });
        catalog.relationships.push({
            left: "campaign_scenarios.scenario_id",
            right: "scenario_response_results.scenario_id",
            cardinality: "one_to_one",
        });
    }

    if (options.includeResponseStatistics === true) {
        catalog.queries.push({
            id: "response_statistics",
            file: "response_statistics.sql",
            grain: "one row per synthetic response metric",
            datasets: ["campaign_response_statistics"],
        });
    }

    const artifacts: FoilQueryArtifact[] = [
        {
            relativePath: "queries/catalog.json",
            content: `${JSON.stringify(catalog, null, 4)}\n`,
        },
        {
            relativePath: "queries/campaign_summary.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, technology, machine_id,
       machine_model_version, classification, objective, compiled_at_utc
FROM ${registry}
WHERE campaign_id = :campaign_id
ORDER BY compiled_at_utc DESC;
`,
        },
        {
            relativePath: "queries/scenario_matrix.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, scenario_index, scenario_id, parameters_json
FROM ${scenarios}
WHERE campaign_id = :campaign_id
ORDER BY scenario_index;
`,
        },
        {
            relativePath: "queries/scenario_parameters.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, scenario_id, parameter_path,
       parameter_value_json, parameter_value_numeric
FROM ${scenarioParameters}
WHERE campaign_id = :campaign_id
ORDER BY scenario_id, parameter_path;
`,
        },
        {
            relativePath: "queries/design_statistics.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, parameter_path, value_count,
       mean_value, stddev_value, min_value, max_value
FROM ${statistics}
WHERE campaign_id = :campaign_id
ORDER BY parameter_path;
`,
        },
        {
            relativePath: "queries/parameter_values.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, parameter_path, value_index,
       parameter_value_json, parameter_value_numeric
FROM ${parameters}
WHERE campaign_id = :campaign_id
ORDER BY parameter_path, value_index;
`,
        },
    ];

    if (options.includeSyntheticResponse === true) {
        artifacts.push({
            relativePath: "queries/scenario_response.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, scenario_id, model_version,
       result_classification, available_fluid_power_kw, capture_proxy,
       mechanical_power_proxy_kw, electrical_power_proxy_kw,
       efficiency_proxy, energy_proxy_kwh, load_proxy_n, assumptions_json
FROM ${responses}
WHERE campaign_id = :campaign_id
ORDER BY scenario_id;
`,
        });
    }

    if (options.includeResponseStatistics === true) {
        artifacts.push({
            relativePath: "queries/response_statistics.sql",
            content:
                sqlHeader(campaign) +
                `SELECT campaign_id, source_hash, result_classification, metric,
       value_count, mean_value, stddev_value, min_value, max_value
FROM ${responseStatistics}
WHERE campaign_id = :campaign_id
ORDER BY metric;
`,
        });
    }

    return artifacts;
}
